# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-09 00:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProfilePicture', models.CharField(max_length=1000)),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=500)),
                ('Mobile', models.CharField(max_length=12)),
                ('National_ID', models.CharField(max_length=40)),
                ('University', models.CharField(max_length=100)),
                ('Faculty', models.CharField(max_length=100)),
                ('Major', models.CharField(max_length=100)),
                ('Minor', models.CharField(max_length=100)),
                ('Expected_GraduationYear', models.CharField(max_length=4)),
            ],
        ),
    ]
